## **Installing Necessary Libraries**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import calendar
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## **Data Loading & Make ready for Preprocessing**

In [3]:
## Loading the data
path ='/content/drive/MyDrive/Thesis/Research Data/Original_Data/3-Hourly Visibility.csv'
df = pd.read_csv(path, low_memory=False)
df

,StationName,StationID,Latitude,Longitude,Year,Month,Time,1,2,3,...,22,23,24,25,26,27,28,29,30,31
0,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,0,4,4,4,...,4,4,4,4,4,4,4,4,4,4
1,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,3,4,4,4,...,4,4,4,4,4,10,4,4,4,4
2,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,6,4,10,10,...,10,4,10,10,10,10,4,4,4,10
3,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,9,4,10,10,...,10,10,10,10,10,10,10,10,10,10
4,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,12,4,10,10,...,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119418,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,9,8,8,7,...,8,5,7,7,7,7,8,8,8,6
119419,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,12,6,6,6,...,5,5,6,6,5,5,5,5,6,5
119420,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,15,5,5,5,...,5,5,5,5,5,5,5,5,5,5
119421,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,18,5,5,5,...,5,5,5,5,5,5,5,5,5,5
119422,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,21,5,5,5,...,4,4,4,4,4,4,4,4,5,4

In [4]:
# Melt the DataFrame into a long format
df_visibility = pd.melt(df, id_vars=['StationName','StationID','Latitude','Longitude', 'Year', 'Month', 'Time'], var_name='Day', value_name='Visibility')
df_visibility

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility
0,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,0,1,4
1,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,3,1,4
2,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,6,1,4
3,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,9,1,4
4,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,12,1,4
...,...,...,...,...,...,...,...,...,...
3702108,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,9,31,6
3702109,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,12,31,5
3702110,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,15,31,5
3702111,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,18,31,5
3702112,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,21,31,4

In [5]:
## Find the datatypes of the columns
df_visibility.dtypes

StationName    object
StationID       int64
Latitude       object
Longitude      object
Year            int64
Month           int64
Time            int64
Day            object
Visibility     object
dtype: object

In [6]:
df_visibility.shape

(3702113, 9)

In [7]:
# Find unique values in 'Month column
df_visibility['StationName'].unique()

array(['Dhaka', 'Tangail', 'Mymensingh', 'Faridpur', 'Madaripur',
       'Srimangal', 'Sylhet', 'Bogura', 'Dinajpur', 'Ishurdi',
       ' Rajshahi', 'Saidpur', 'Chadanga', 'Jessore', 'Khulna', 'Mongla',
       'Satkhira', 'Barishal', 'Bhola', 'Khepupara', 'Patuakhali',
       'Chandpur', 'Teknaf', 'Chittagong', 'Comilla', "Cox'sBazar",
       'Feni', 'Hatiya', 'Kutubdia', 'Maijdee_court', 'Rangmati',
       'Sandwip', 'Ambagan(Ctg.)', 'Sitakunda', 'Gopalgonj', 'Tarash',
       'Natrakina', 'Rajarhat', 'Badalgachhi', 'Dimla', 'Kumarkhali'],
      dtype=object)

In [8]:
# Count unique StationIDs
num_unique_station_name = df_visibility['StationName'].nunique()

print(f"Count of unique Station IDs: {num_unique_station_name}")

Count of unique Station IDs: 41

In [9]:
# Find unique values in 'Year column
df_visibility['StationID'].unique()

array([11111, 41909, 10609, 11505, 11513, 10724, 10705, 10408, 10120,
       10910, 10320, 41858, 41926, 11407, 11604, 41947, 41958, 11610,
       11704, 11706, 12110, 12103, 11316, 11929, 11921, 11313, 11927,
       11805, 11814, 11925, 11809, 12007, 11916, 41977, 11912, 41938,
       41897, 41888, 41856, 41881, 41851, 41927])

In [10]:
# Count unique StationIDs
num_unique_station_ids = df_visibility['StationID'].nunique()

print(f"Count of unique Station IDs: {num_unique_station_ids}")

Count of unique Station IDs: 42

In [11]:
# Find unique values in 'Month column
df_visibility['Latitude'].unique()

array(['23Deg.46Mts.N', '24Deg.15Mts.N', '24Deg.43Mts.N', '23Deg.36Mts.N',
       '23Deg.10Mts.N', '24Deg.18Mts.N', '24Deg.54Mts.N', '24Deg.51Mts.N',
       '25Deg.39Mts.N', '24Deg.8Mts.N', '24Deg.22Mts.N', '25Deg.47Mts.N',
       '23Deg.39Mts.N', '23Deg.11Mts.N', '22Deg.47Mts.N', '22Deg.20Mts.N',
       '22Deg.43Mts.N', '22Deg.45Mts.N', '22Deg.41Mts.N', '21Deg.59Mts.N',
       '23Deg.16Mts.N', '20Deg.52Mts.N', '22Deg.16Mts.N', '23Deg.26Mts.N',
       '21Deg.26Mts.N', '23Deg.2Mts.N', '22Deg.26Mts.N', '21Deg.49Mts.N',
       '22Deg.52Mts.N', '22Deg.32Mts.N', '22Deg.29Mts.N', '22Deg.21Mts.N',
       '23Deg.35Mts.N', '24Deg.56Mts.N', '25Deg.51Mts.N', '24Deg.58Mts.N',
       '26Deg. 9Mts.N', '23Deg.52Mts.N'], dtype=object)

In [12]:
# Count unique StationIDs
num_unique_latitude = df_visibility['Latitude'].nunique()

print(f"Count of unique Station IDs: {num_unique_latitude}")

Count of unique Station IDs: 38

In [13]:
# Find unique values in 'Month column
df_visibility['Longitude'].unique()

array(['90Deg.23Mts.E', '89Deg.55Mts.E', '90Deg.26Mts.E', '89Deg.51Mts.E',
       '90Deg.11Mts.E', '91Deg.44Mts.E', '91Deg.53Mts.E', '89Deg.22Mts.E',
       '88Deg.41Mts.E', '89Deg.3Mts.E', '88Deg.42Mts.E', '88Deg.53Mts.E',
       '88Deg.52Mts.E', '89Deg.10Mts.E', '89Deg.32Mts.E', '89Deg.36Mts.E',
       '89Deg.5Mts.E', '90Deg.20Mts.E', '90Deg.39Mts.E', '90Deg.14Mts.E',
       '90Deg.42Mts.E', '92Deg.18Mts.E', '91Deg.49Mts.E', '91Deg.11Mts.E',
       '91Deg.56Mts.E', '91Deg.25Mts.E', '91Deg.6Mts.E', '91Deg.51Mts.E',
       '92Deg.12Mts.E', '91Deg.26Mts.E', '91Deg.42Mts.E', '89Deg.50Mts.E',
       '89Deg.23Mts.E', '90Deg.44Mts.E', '88Deg.54Mts.E', '88Deg.56Mts.E',
       '89Deg.15Mts.E'], dtype=object)

In [14]:
df_visibility['Longitude'].nunique()

37

In [15]:
df_visibility['Year'].unique()

array([1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023])

In [16]:
df_visibility['Year'].nunique()

43

In [17]:
# Find unique values in 'Month column
df_visibility['Month'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
# Find unique values in 'Day column
df_visibility['Day'].unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31'], dtype=object)

In [19]:
# Find data types 'Day column
df_visibility['Day'].dtypes

dtype('O')

In [20]:
# Convert the Day column to numeric
df_visibility['Day'] = pd.to_numeric(df_visibility['Day'])
df_visibility

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility
0,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,0,1,4
1,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,3,1,4
2,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,6,1,4
3,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,9,1,4
4,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,12,1,4
...,...,...,...,...,...,...,...,...,...
3702108,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,9,31,6
3702109,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,12,31,5
3702110,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,15,31,5
3702111,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,18,31,5
3702112,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,21,31,4

In [21]:
## Find the datatypes of the columns again
df_visibility.dtypes

StationName    object
StationID       int64
Latitude       object
Longitude      object
Year            int64
Month           int64
Time            int64
Day             int64
Visibility     object
dtype: object

In [22]:
# Find unique values in 'Time' column
df_visibility['Time'].unique()

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [23]:
# Find unique values in 'Visibility' column
df_visibility['Visibility'].unique()

array(['4', '****', '10', '9', '0.4', '2', '1', '54', '5', '2.5', '4.5',
       '3', '6', '5.5', '3.5', '20.2', '1.5', '0.2', '0.3', '0.5', '0.6',
       '0.8', '0.9', '7', '0.1', '2.6', '8', '12', '5.6', '41', '3.2',
       '0.7', '1.6', '3.8', '1.8', '1.1', '91.7', '1.2', '5.2', '19.1',
       '6.9', '9.6', '5.7', '40.1', '8.2', '2.8', '50', '80.4', '6.2',
       '9.2', '2.2', '10.3', '4.6', '10.1', '20.4', '91.3', '20.3', '1.3',
       '2.3', '1.4', '2.4', '9.5', '2.7', '8.4', '20', '40.4', '20.5',
       '1.7', '9.4', '3.4', '5.4', '12.2', '40.2', '50.1', '50.2', '10.2',
       '25.2', '26.9', '20.9', '25.9', '7.4', '30.2', '40', '5.8', '5.9',
       '72', '8.8', '20.1', '13', '11', '92.1', '74', '50.5', '4.2', '45',
       '6.6', '40.5', '3.3', '4.8', '4.1', '4.9', '52', '60', '2.9',
       '3.6', '1.9', '3.1', '2.1', '3.7', '15', '18', '21', '66.2', '4.3',
       '69.3', '18.4', '8.1', '14', '84', '28', '16', '8.6', '22.3', '26',
       '4.4', '66.1', '30.3', '6.8', '22', '62.1', '45.9', '78.2', '60.1',
       '51.7', '35.9', '21.3', '6.5', '34.7', '55', '79.9', '13.4', '7.6',
       '7.1', '60.5', '7.2', '8.7', '9.3', '35.2', '16.2', '63.9', '10.9',
       '30.4', '25.4', '57.1', '70.1', '5.3', '8.3', '44.3', '8.5',
       '12.3', '42', '4.7', '10.8', '25.8', '54.9', '95.1', '69.5',
       '53.6', '6.4', '30', '6.3', '9.9', '24', '5.1', '22.5', '94.2',
       '70', '33', '6.1', '9.1', '80.6', '25', '16.1', '30.1', '18.3',
       '6.7', '65', '50.6', '35.4', '10.6', '44.1', '60.6', '7.3', '3.9',
       '94.4', '44.2', '90.2', '7.7', '22.1', '33.5', '66', '60.2',
       '33.1', '20.6', '98', '8.9', '46', '30.6', '99', '99.5', '22.2',
       '28.7', '20.7', '10.5', '50.3', '34.6', '9.7', '44.5', '89.1',
       '23.2', '70.9', '40.6', '58', '97', '10.4', '17', '25.6', '15.5',
       '23.3', '30.5', '59.9', '7.8', '70.2', '25.1', '34', '45.2', '39',
       '7.5', '24.3', '42.9', '60.8', '14.6', '44.4', '28.4', '70.4',
       '35.1', '78', '32', '44', '96', '29.9', '19.8', '40.3', '27',
       '70.5', '45.4', '92.4', '93.9', '17.5', '7.9', '16.3', '67.3',
       '19', '90.1', '90.6', '57', '35', '80', '50.9', '90.4', '96.8',
       '90', '14.5', '95.3', '12.4', '81', '36.9', '26.1', '91', '33.9',
       '99.1', '38.7', '90.3', '11.4', '56.2', '80.8', '70.3', '97.1',
       '57.7', '94.3', '60.9', '23', '37.5', '80.2', '20.8', '15.3',
       '44.6', '96.4', '57.2', '36.5', '97.2', '17.8', '64', '29', '80.1',
       '44.9', '60.4', '56.1', '27.6', '24.4', '82', '71', '56.6', '90.5',
       '34.3', '55.1', '11.3', '95.6', '99.7', '30.7', '85.3', '50.4',
       '96.6', '50.7', '13.5', '68.3', '64.6', '94', '92', '44.7', '69',
       '68.4', '16.9', '33.4', '97.5', '32.9', '24.1', '9.8', '35.6',
       '40.9', '58.2', '24.5', '61', '14.4', '52.1', '62.9', '30.9',
       '12.9', '51.3', '43.2', '85', '16.6', '56', '35.3', '15.4', '74.1',
       '29.5', '95.7', '52.9', '22.9', '88.4', '74.4', '93.2', '92.9',
       '31.8', '16.7', '11.6', '13.6', '36', '66.3', '11.2', '51.9',
       '65.5', '79.6', '58.4', '40.7', '91.2', '48.5', '24.2', '21.7',
       '61.7', '27.5', '93.7', '80.3', '94.1', '60.7', '34.1', '35.5',
       '28.1', '25.7', '23.4', '25.3', '96.1', '88', '68.2', '63', nan,
       '38.6', '16.5', '22.8', '19.4', '14.3', '33.6', '98.8', '15.8'],
      dtype=object)

## **Handling Missing value and Unwanted Symbol**

In [24]:
## Count the number of '****' in the value column
df_visibility['Visibility'][df_visibility['Visibility'] == '****'].count()

np.int64(423957)

In [25]:
# Filter rows where 'Visibility' is '****'
rows_with_asterisks = df_visibility[df_visibility['Visibility'] == '****']

# Display the rows
rows_with_asterisks

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility
7,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,21,1,****
15,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,2,21,1,****
23,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,3,21,1,****
31,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,4,21,1,****
39,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,5,21,1,****
...,...,...,...,...,...,...,...,...,...
3700940,Badalgachhi,41881,24Deg.58Mts.N,88Deg.54Mts.E,2022,11,9,31,****
3700941,Badalgachhi,41881,24Deg.58Mts.N,88Deg.54Mts.E,2022,11,12,31,****
3700942,Badalgachhi,41881,24Deg.58Mts.N,88Deg.54Mts.E,2022,11,15,31,****
3700943,Badalgachhi,41881,24Deg.58Mts.N,88Deg.54Mts.E,2022,11,18,31,****
3700944,Badalgachhi,41881,24Deg.58Mts.N,88Deg.54Mts.E,2022,11,21,31,****

In [26]:
# Filter rows where 'Visibility' is '****'
rows_with_asterisks = df_visibility[df_visibility['Visibility'] == '****']

# Group by 'StationName' and display the results
station_specific_results = rows_with_asterisks.groupby('StationName')

# Display results for each station
for station, data in station_specific_results:
    print(f"Station: {station}")
    print(data, '\n')

Station:  Rajshahi
        StationName  StationID       Latitude      Longitude  Year  Month  \
33892      Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  1981      1
33893      Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  1981      1
33894      Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  1981      1
33895      Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  1981      1
33901      Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  1981      2
...             ...        ...            ...            ...   ...    ...
3618177    Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  2000      8
3618191    Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  2000     10
3618192    Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  2000     10
3618193    Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  2000     10
3618210    Rajshahi      10320  24Deg.22Mts.N  88Deg.42Mts.E  2001      1

         Time  Day Visibility
33892      12    1       ****
33893      15    1       ****
33894      18    1       ****
33895      21    1       ****
33901      15    1       ****
...       ...  ...        ...
3618177    21   31       ****
3618191    15   31       ****
3618192    18   31       ****
3618193    21   31       ****
3618210     0   31       ****

[21176 rows x 9 columns]

Station: Ambagan(Ctg.)
           StationName  StationID       Latitude      Longitude  Year  Month  \
109940   Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999      3
109941   Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999      3
109942   Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999      3
109948   Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999      4
109949   Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999      4
...                ...        ...            ...            ...   ...    ...
3692697  Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999     12
3692701  Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999     12
3692702  Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999     12
3692703  Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999     12
3692704  Ambagan(Ctg.)      41977  22Deg.21Mts.N  91Deg.49Mts.E  1999     12

         Time  Day Visibility
109940     15    1       ****
109941     18    1       ****
109942     21    1       ****
109948     15    1       ****
109949     18    1       ****
...       ...  ...        ...
3692697     0   31       ****
3692701    12   31       ****
3692702    15   31       ****
3692703    18   31       ****
3692704    21   31       ****

[781 rows x 9 columns]

Station: Badalgachhi
         StationName  StationID       Latitude      Longitude  Year  Month  \
1789897  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2019     12
2984226  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2021      1
3103545  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2019     11
3103655  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2021      2
3461923  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2021      2
...              ...        ...            ...            ...   ...    ...
3700940  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2022     11
3700941  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2022     11
3700942  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2022     11
3700943  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2022     11
3700944  Badalgachhi      41881  24Deg.58Mts.N  88Deg.54Mts.E  2022     11

         Time  Day Visibility
1789897     0   15       ****
2984226     9   25       ****
3103545     9   26       ****
3103655     3   26       ****
3461923     0   29       ****
...       ...  ...        ...
3700940     9   31       ****
3700941    12   31       ****
3700942    15   31       ****
3700943    18   31       ****
3700944    21   31       ****

[116 rows x 9 columns]

Station: Barishal
        StationName  StationID       Latitude      Longitude  Year  Month  \
59524      Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  1981      1
59525      Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  1981      1
59526      Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  1981      1
59527      Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  1981      1
59533      Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  1981      2
...             ...        ...            ...            ...   ...    ...
3644094    Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  2003      8
3644095    Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  2003      8
3644096    Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  2003      8
3644097    Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  2003      8
3645947    Barishal      11704  22Deg.45Mts.N  90Deg.20Mts.E  2022     12

         Time  Day Visibility
59524      12    1       ****
59525      15    1       ****
59526      18    1       ****
59527      21    1       ****
59533      15    1       ****
...       ...  ...        ...
3644094    12   31       ****
3644095    15   31       ****
3644096    18   31       ****
3644097    21   31       ****
3645947     3   31       ****

[24670 rows x 9 columns]

Station: Bhola
        StationName  StationID       Latitude      Longitude  Year  Month  \
63360         Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1981      1
63364         Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1981      1
63365         Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1981      1
63366         Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1981      1
63367         Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1981      1
...             ...        ...            ...            ...   ...    ...
3647290       Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1993     12
3647294       Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1993     12
3647295       Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1993     12
3647296       Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1993     12
3647297       Bhola      11706  22Deg.41Mts.N  90Deg.39Mts.E  1993     12

         Time  Day Visibility
63360       0    1       ****
63364      12    1       ****
63365      15    1       ****
63366      18    1       ****
63367      21    1       ****
...       ...  ...        ...
3647290     0   31       ****
3647294    12   31       ****
3647295    15   31       ****
3647296    18   31       ****
3647297    21   31       ****

[16753 rows x 9 columns]

Station: Bogura
        StationName  StationID       Latitude      Longitude  Year  Month  \
23328        Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  1981      1
23332        Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  1981      1
23333        Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  1981      1
23334        Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  1981      1
23335        Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  1981      1
...             ...        ...            ...            ...   ...    ...
3607746      Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  2004      1
3607750      Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  2004      1
3607751      Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  2004      1
3607752      Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  2004      1
3607753      Bogura      10408  24Deg.51Mts.N  89Deg.22Mts.E  2004      1

         Time  Day Visibility
23328       0    1       ****
23332      12    1       ****
23333      15    1       ****
23334      18    1       ****
23335      21    1       ****
...       ...  ...        ...
3607746     0   31       ****
3607750    12   31       ****
3607751    15   31       ****
3607752    18   31       ****
3607753    21   31       ****

[22997 rows x 9 columns]

Station: Chadanga
        StationName  StationID       Latitude      Longitude  Year  Month  \
43393      Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  1990      1
43396      Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  1990      1
43397      Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  1990      1
43398      Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  1990      1
43399      Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  1990      1
...             ...        ...            ...            ...   ...    ...
3626272    Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  1994     12
3626273    Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  1994     12
3626274    Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  1999      1
3626278    Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  1999      1
3626650    Chadanga      41926  23Deg.39Mts.N  88Deg.52Mts.E  2002     12

         Time  Day Visibility
43393       3    1       ****
43396      12    1       ****
43397      15    1       ****
43398      18    1       ****
43399      21    1       ****
...       ...  ...        ...
3626272    18   31       ****
3626273    21   31       ****
3626274     0   31       ****
3626278    12   31       ****
3626650     0   31       ****

[2387 rows x 9 columns]

Station: Chandpur
        StationName  StationID       Latitude      Longitude  Year  Month  \
74004      Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  1984     11
74005      Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  1984     11
74006      Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  1984     11
74007      Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  1984     11
74012      Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  1984     12
...             ...        ...            ...            ...   ...    ...
3658105    Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  2002      7
3658111    Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  2002      8
3658112    Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  2002      8
3658113    Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  2002      8
3660101    Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  2023      5

         Time  Day Visibility
74004      12    1       ****
74005      15    1       ****
74006      18    1       ****
74007      21    1       ****
74012      12    1       ****
...       ...  ...        ...
3658105    21   31       ****
3658111    15   31       ****
3658112    18   31       ****
3658113    21   31       ****
3660101     9   31       ****

[16371 rows x 9 columns]

Station: Chittagong
        StationName  StationID       Latitude      Longitude  Year  Month  \
80803    Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  1984     10
80946    Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  1986      4
80947    Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  1986      4
80951    Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  1986      4
81424    Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  1991      4
...             ...        ...            ...            ...   ...    ...
3666381  Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  2022     11
3666382  Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  2022     11
3666383  Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  2022     11
3666384  Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  2022     11
3666385  Chittagong      11921  22Deg.16Mts.N  91Deg.49Mts.E  2022     11

         Time  Day Visibility
80803       9    1       ****
80946       6    1       ****
80947       9    1       ****
80951      21    1       ****
81424       0    1       ****
...       ...  ...        ...
3666381     9   31       ****
3666382    12   31       ****
3666383    15   31       ****
3666384    18   31       ****
3666385    21   31       ****

[4739 rows x 9 columns]

Station: Comilla
        StationName  StationID       Latitude      Longitude  Year  Month  \
83712       Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  1981      1
83716       Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  1981      1
83717       Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  1981      1
83718       Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  1981      1
83719       Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  1981      1
...             ...        ...            ...            ...   ...    ...
3669274     Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  2013     12
3669275     Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  2013     12
3669473     Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  2015     12
3670138     Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  2022     12
3670139     Comilla      11313  23Deg.26Mts.N  91Deg.11Mts.E  2022     12

         Time  Day Visibility
83712       0    1       ****
83716      12    1       ****
83717      15    1       ****
83718      18    1       ****
83719      21    1       ****
...       ...  ...        ...
3669274     0   31       ****
3669275     3   31       ****
3669473    21   31       ****
3670138     0   31       ****
3670139     3   31       ****

[19170 rows x 9 columns]

Station: Cox'sBazar
        StationName  StationID       Latitude      Longitude  Year  Month  \
87564    Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1981      2
87565    Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1981      2
87566    Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1981      2
87567    Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1981      2
87572    Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1981      3
...             ...        ...            ...            ...   ...    ...
3670528  Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1983     12
3670529  Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1983     12
3670630  Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1985      1
3670934  Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1988      3
3671305  Cox'sBazar      11927  21Deg.26Mts.N  91Deg.56Mts.E  1992      1

         Time  Day Visibility
87564      12    1       ****
87565      15    1       ****
87566      18    1       ****
87567      21    1       ****
87572      12    1       ****
...       ...  ...        ...
3670528    18   31       ****
3670529    21   31       ****
3670630    12   31       ****
3670934    12   31       ****
3671305    21   31       ****

[4743 rows x 9 columns]

Station: Dhaka
        StationName  StationID       Latitude      Longitude  Year  Month  \
7             Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      1
15            Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      2
23            Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      3
31            Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      4
39            Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      5
...             ...        ...            ...            ...   ...    ...
3582885       Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1983      1
3582886       Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1983      1
3582887       Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1983      1
3582888       Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1983      1
3582889       Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1983      1

         Time  Day Visibility
7          21    1       ****
15         21    1       ****
23         21    1       ****
31         21    1       ****
39         21    1       ****
...       ...  ...        ...
3582885     9   31       ****
3582886    12   31       ****
3582887    15   31       ****
3582888    18   31       ****
3582889    21   31       ****

[860 rows x 9 columns]

Station: Dinajpur
        StationName  StationID       Latitude      Longitude  Year  Month  \
26976      Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1990      1
26977      Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1990      1
26980      Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1990      1
26981      Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1990      1
26982      Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1990      1
...             ...        ...            ...            ...   ...    ...
3620986    Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1995     12
3620990    Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1995     12
3620991    Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1995     12
3620992    Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1995     12
3620993    Dinajpur      10120  25Deg.39Mts.N  88Deg.41Mts.E  1995     12

         Time  Day Visibility
26976       0    1       ****
26977       3    1       ****
26980      12    1       ****
26981      15    1       ****
26982      18    1       ****
...       ...  ...        ...
3620986     0   31       ****
3620990    12   31       ****
3620991    15   31       ****
3620992    18   31       ****
3620993    21   31       ****

[15826 rows x 9 columns]

Station: Faridpur
        StationName  StationID       Latitude      Longitude  Year  Month  \
10373      Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  1981      1
10374      Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  1981      1
10375      Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  1981      1
10381      Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  1981      2
10382      Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  1981      2
...             ...        ...            ...            ...   ...    ...
3594496    Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  1995     12
3594497    Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  1995     12
3594874    Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  2002     12
3594881    Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  2002     12
3595066    Faridpur      11505  23Deg.36Mts.N  89Deg.51Mts.E  2004     12

         Time  Day Visibility
10373      15    1       ****
10374      18    1       ****
10375      21    1       ****
10381      15    1       ****
10382      18    1       ****
...       ...  ...        ...
3594496    18   31       ****
3594497    21   31       ****
3594874     0   31       ****
3594881    21   31       ****
3595066     0   31       ****

[18779 rows x 9 columns]

Station: Feni
        StationName  StationID      Latitude      Longitude  Year  Month  \
91299          Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  1981      1
91300          Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  1981      1
91301          Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  1981      1
91302          Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  1981      1
91303          Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  1981      2
...             ...        ...           ...            ...   ...    ...
3677545        Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  2022      2
3677561        Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  2022      4
3677577        Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  2022      6
3677601        Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  2022      9
3677617        Feni      11805  23Deg.2Mts.N  91Deg.25Mts.E  2022     11

         Time  Day Visibility
91299      12    1       ****
91300      15    1       ****
91301      18    1       ****
91302      21    1       ****
91303       0    1       ****
...       ...  ...        ...
3677545     0   31       ****
3677561     0   31       ****
3677577     0   31       ****
3677601     0   31       ****
3677617     0   31       ****

[15003 rows x 9 columns]

Station: Gopalgonj
        StationName  StationID      Latitude      Longitude  Year  Month  \
235126    Gopalgonj      41938  23Deg.2Mts.N  89Deg.50Mts.E  2020      4
354341    Gopalgonj      41938  23Deg.2Mts.N  89Deg.50Mts.E  2018      2
354342    Gopalgonj      41938  23Deg.2Mts.N  89Deg.50Mts.E  2018      2
951729    Gopalgonj      41938  23Deg.2Mts.N  89Deg.50Mts.E  2020     12
951733    Gopalgonj      41938  23Deg.2Mts.N  89Deg.50Mts.E  2020     12

In [27]:
# To find the null values
df_visibility.isnull().sum()

StationName        0
StationID          0
Latitude           0
Longitude          0
Year               0
Month              0
Time               0
Day                0
Visibility     67368
dtype: int64

In [28]:
# Replace '****' with NaN in the original DataFrame
df_visibility.loc[df_visibility['Visibility'] == '****', 'Visibility'] = np.nan

In [29]:
# To find the null values
df_visibility.isnull().sum()

StationName         0
StationID           0
Latitude            0
Longitude           0
Year                0
Month               0
Time                0
Day                 0
Visibility     491325
dtype: int64

In [30]:
# Step 2: Convert 'Visibility' to numeric, coercing errors (turn non-numeric to NaN)
df_visibility['Visibility'] = pd.to_numeric(df_visibility['Visibility'], errors='coerce')

# Group by StationName, Month, Day, and Time, and calculate the mean for each group
Visibility_mean = df_visibility.groupby(['StationName', 'Month', 'Day', 'Time'])['Visibility'].transform('mean')

# Replace '*****' (NaN values) with the mean of the same station, month, day, and time
df_visibility['Visibility'] = df_visibility['Visibility'].fillna(Visibility_mean)

# Verify the result
print(df_visibility)

        StationName  StationID       Latitude      Longitude  Year  Month  \
0             Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      1
1             Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      1
2             Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      1
3             Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      1
4             Dhaka      11111  23Deg.46Mts.N  90Deg.23Mts.E  1981      1
...             ...        ...            ...            ...   ...    ...
3702108  Kumarkhali      41927  23Deg.52Mts.N  89Deg.15Mts.E  2023     12
3702109  Kumarkhali      41927  23Deg.52Mts.N  89Deg.15Mts.E  2023     12
3702110  Kumarkhali      41927  23Deg.52Mts.N  89Deg.15Mts.E  2023     12
3702111  Kumarkhali      41927  23Deg.52Mts.N  89Deg.15Mts.E  2023     12
3702112  Kumarkhali      41927  23Deg.52Mts.N  89Deg.15Mts.E  2023     12

         Time  Day  Visibility
0           0    1         4.0
1           3    1         4.0
2           6    1         4.0
3           9    1         4.0
4          12    1         4.0
...       ...  ...         ...
3702108     9   31         6.0
3702109    12   31         5.0
3702110    15   31         5.0
3702111    18   31         5.0
3702112    21   31         4.0

[3702113 rows x 9 columns]

In [31]:
# Check it again to  find the null values
df_visibility.isnull().sum()

StationName        0
StationID          0
Latitude           0
Longitude          0
Year               0
Month              0
Time               0
Day                0
Visibility     63101
dtype: int64

In [32]:
# Check rows where 'Visibility' is still NaN after replacement
rows_with_nan = df_visibility[df_visibility['Visibility'].isna()]

# If there are still rows with NaN, inspect them
rows_with_nan

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility
108871,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,1,21,1,NaN
108877,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,2,15,1,NaN
108878,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,2,18,1,NaN
108879,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,2,21,1,NaN
108886,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,3,18,1,NaN
...,...,...,...,...,...,...,...,...,...
3702060,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,6,9,31,NaN
3702061,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,6,12,31,NaN
3702062,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,6,15,31,NaN
3702063,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,6,18,31,NaN
3702064,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,6,21,31,NaN

In [33]:
# Sample: Define valid days for each month (for non-leap years)
valid_days_per_month = {
    1: 31, 2: 28, 3: 31, 4: 30, 5: 31, 6: 30,
    7: 31, 8: 31, 9: 30, 10: 31, 11: 30, 12: 31
}

# Adjust for leap years (for February only)
def is_leap_year(year):
    return (year % 4 == 0 and (year % 100 != 0 or year % 400 == 0))

# Add a column to check if a year is a leap year
df_visibility['IsLeapYear'] = df_visibility['Year'].apply(is_leap_year)

# Adjust February days for leap years
df_visibility.loc[df_visibility['IsLeapYear'], 'ValidDays'] = df_visibility.loc[df_visibility['IsLeapYear'], 'Month'].apply(lambda month: 29 if month == 2 else valid_days_per_month[month])
df_visibility.loc[~df_visibility['IsLeapYear'], 'ValidDays'] = df_visibility.loc[~df_visibility['IsLeapYear'], 'Month'].apply(lambda month: valid_days_per_month[month])

In [34]:
# Remove rows where 'Day' is greater than the valid days for that month
df_visibility = df_visibility[df_visibility['Day'] <= df_visibility['ValidDays']]

In [35]:
df_visibility

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility,IsLeapYear,ValidDays
0,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,0,1,4.0,False,31.0
1,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,3,1,4.0,False,31.0
2,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,6,1,4.0,False,31.0
3,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,9,1,4.0,False,31.0
4,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,12,1,4.0,False,31.0
...,...,...,...,...,...,...,...,...,...,...,...
3702108,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,9,31,6.0,False,31.0
3702109,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,12,31,5.0,False,31.0
3702110,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,15,31,5.0,False,31.0
3702111,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,18,31,5.0,False,31.0
3702112,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,21,31,4.0,False,31.0

In [36]:
# Check rows where 'Visibility' is still NaN after replacement
rows_with_nan = df_visibility[df_visibility['Visibility'].isna()]

# If there are still rows with NaN, inspect them
rows_with_nan

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility,IsLeapYear,ValidDays
108871,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,1,21,1,NaN,False,31.0
108877,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,2,15,1,NaN,False,28.0
108878,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,2,18,1,NaN,False,28.0
108879,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,2,21,1,NaN,False,28.0
108886,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1983,3,18,1,NaN,False,31.0
...,...,...,...,...,...,...,...,...,...,...,...
3692594,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1993,12,0,31,NaN,False,31.0
3692598,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1993,12,12,31,NaN,False,31.0
3692599,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1993,12,15,31,NaN,False,31.0
3692600,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1993,12,18,31,NaN,False,31.0
3692601,Sandwip,11916,22Deg.29Mts.N,91Deg.26Mts.E,1993,12,21,31,NaN,False,31.0

In [37]:
# Check it again to  find the null values
df_visibility.isnull().sum()

StationName       0
StationID         0
Latitude          0
Longitude         0
Year              0
Month             0
Time              0
Day               0
Visibility     3876
IsLeapYear        0
ValidDays         0
dtype: int64

In [38]:
# Check if all Visibility values within each group are NaN
nan_groups = df_visibility.groupby(['StationName', 'Month', 'Day', 'Time'])['Visibility'].apply(lambda x: x.isna().all())

# Get the combinations that have all NaN Visibility values
print(nan_groups[nan_groups].index)  # This will show you the groups where all Visibility values are NaN

MultiIndex([('Chittagong', 12, 31,  0),
            ('Chittagong', 12, 31,  3),
            ('Chittagong', 12, 31,  6),
            ('Chittagong', 12, 31,  9),
            ('Chittagong', 12, 31, 12),
            ('Chittagong', 12, 31, 15),
            ('Chittagong', 12, 31, 18),
            ('Chittagong', 12, 31, 21),
            (      'Feni',  3, 30,  0),
            (      'Feni',  3, 31,  0),
            ...
            (   'Sandwip',  9, 29, 18),
            (   'Sandwip',  9, 29, 21),
            (   'Sandwip', 10, 31, 15),
            (   'Sandwip', 10, 31, 18),
            (   'Sandwip', 10, 31, 21),
            (   'Sandwip', 12, 31,  0),
            (   'Sandwip', 12, 31, 12),
            (   'Sandwip', 12, 31, 15),
            (   'Sandwip', 12, 31, 18),
            (   'Sandwip', 12, 31, 21)],
           names=['StationName', 'Month', 'Day', 'Time'], length=332)

In [39]:
# Forward fill missing values in 'Visibility'
df_visibility['Visibility'] = df_visibility['Visibility'].fillna(method='ffill')

# Verify the result by checking if there are any NaN values left
print(df_visibility.isnull().sum())

<ipython-input-39-e61ff089fd0f>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_visibility['Visibility'] = df_visibility['Visibility'].fillna(method='ffill')
<ipython-input-39-e61ff089fd0f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_visibility['Visibility'] = df_visibility['Visibility'].fillna(method='ffill')

StationName    0
StationID      0
Latitude       0
Longitude      0
Year           0
Month          0
Time           0
Day            0
Visibility     0
IsLeapYear     0
ValidDays      0
dtype: int64

In [40]:
# Check it again to  find the null values
df_visibility.isnull().sum()

StationName    0
StationID      0
Latitude       0
Longitude      0
Year           0
Month          0
Time           0
Day            0
Visibility     0
IsLeapYear     0
ValidDays      0
dtype: int64

In [41]:
df_visibility = df_visibility.drop(columns=['IsLeapYear', 'ValidDays'])

In [42]:
df_visibility

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility
0,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,0,1,4.0
1,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,3,1,4.0
2,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,6,1,4.0
3,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,9,1,4.0
4,Dhaka,11111,23Deg.46Mts.N,90Deg.23Mts.E,1981,1,12,1,4.0
...,...,...,...,...,...,...,...,...,...
3702108,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,9,31,6.0
3702109,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,12,31,5.0
3702110,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,15,31,5.0
3702111,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,18,31,5.0
3702112,Kumarkhali,41927,23Deg.52Mts.N,89Deg.15Mts.E,2023,12,21,31,4.0

## **Coverting Latitude and Longitude to Numerical Value**

In [43]:
df_visibility.dtypes

StationName     object
StationID        int64
Latitude        object
Longitude       object
Year             int64
Month            int64
Time             int64
Day              int64
Visibility     float64
dtype: object

In [44]:
def convert_to_decimal(deg_min, direction):
    """
    Converts degree-minute format to decimal degrees.
    Example Input: "23Deg.46Mts.N" -> Output: 23.7667
    """
    parts = deg_min.split("Deg.")
    degrees = float(parts[0])
    minutes = float(parts[1].split("Mts.")[0])

    decimal = degrees + (minutes / 60)

    # Convert South/West to negative
    if direction in ["S", "W"]:
        decimal = -decimal

    return decimal

# Example usage
latitude = convert_to_decimal("23Deg.46Mts.", "N")
longitude = convert_to_decimal("90Deg.23Mts.", "E")

print(latitude, longitude)  # Output: 23.7667, 90.3833

23.766666666666666 90.38333333333334

In [45]:
df_visibility["Latitude"] = df_visibility["Latitude"].apply(lambda x: convert_to_decimal(x[:-1], x[-1]))  # Extract last character (N/S)
df_visibility["Longitude"] = df_visibility["Longitude"].apply(lambda x: convert_to_decimal(x[:-1], x[-1]))  # Extract last character (E/W)
df_visibility

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility
0,Dhaka,11111,23.766667,90.383333,1981,1,0,1,4.0
1,Dhaka,11111,23.766667,90.383333,1981,1,3,1,4.0
2,Dhaka,11111,23.766667,90.383333,1981,1,6,1,4.0
3,Dhaka,11111,23.766667,90.383333,1981,1,9,1,4.0
4,Dhaka,11111,23.766667,90.383333,1981,1,12,1,4.0
...,...,...,...,...,...,...,...,...,...
3702108,Kumarkhali,41927,23.866667,89.250000,2023,12,9,31,6.0
3702109,Kumarkhali,41927,23.866667,89.250000,2023,12,12,31,5.0
3702110,Kumarkhali,41927,23.866667,89.250000,2023,12,15,31,5.0
3702111,Kumarkhali,41927,23.866667,89.250000,2023,12,18,31,5.0
3702112,Kumarkhali,41927,23.866667,89.250000,2023,12,21,31,4.0

In [46]:
# Check for invalid days (e.g., day > 31 or day > max days in the month)
invalid_dates = df_visibility[(df_visibility['Day'] > 31) | (df_visibility['Month'] > 12)]
print(invalid_dates)

Empty DataFrame
Columns: [StationName, StationID, Latitude, Longitude, Year, Month, Time, Day, Visibility]
Index: []

## **Creating Date Time Column**

In [47]:
import calendar

# Function to check if a date is valid
def is_invalid_date(row):
    days_in_month = calendar.monthrange(row['Year'], row['Month'])[1]
    return row['Day'] > days_in_month

# Remove invalid rows
df_visibility = df_visibility[~df_visibility.apply(is_invalid_date, axis=1)].reset_index(drop=True)

# Convert datetime again
df_visibility['Datetime'] = pd.to_datetime(df_visibility[['Year', 'Month', 'Day']]) + pd.to_timedelta(df_visibility['Time'], unit='h')

print(df_visibility.info())  # Verify that datetime is correctly created

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3634745 entries, 0 to 3634744
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   StationName  object
 1   StationID    int64
 2   Latitude     float64
 3   Longitude    float64
 4   Year         int64
 5   Month        int64
 6   Time         int64
 7   Day          int64
 8   Visibility   float64
 9   Datetime     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(5), object(1)
memory usage: 277.3+ MB
None

In [48]:
df_visibility

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility,Datetime
0,Dhaka,11111,23.766667,90.383333,1981,1,0,1,4.0,1981-01-01 00:00:00
1,Dhaka,11111,23.766667,90.383333,1981,1,3,1,4.0,1981-01-01 03:00:00
2,Dhaka,11111,23.766667,90.383333,1981,1,6,1,4.0,1981-01-01 06:00:00
3,Dhaka,11111,23.766667,90.383333,1981,1,9,1,4.0,1981-01-01 09:00:00
4,Dhaka,11111,23.766667,90.383333,1981,1,12,1,4.0,1981-01-01 12:00:00
...,...,...,...,...,...,...,...,...,...,...
3634740,Kumarkhali,41927,23.866667,89.250000,2023,12,9,31,6.0,2023-12-31 09:00:00
3634741,Kumarkhali,41927,23.866667,89.250000,2023,12,12,31,5.0,2023-12-31 12:00:00
3634742,Kumarkhali,41927,23.866667,89.250000,2023,12,15,31,5.0,2023-12-31 15:00:00
3634743,Kumarkhali,41927,23.866667,89.250000,2023,12,18,31,5.0,2023-12-31 18:00:00
3634744,Kumarkhali,41927,23.866667,89.250000,2023,12,21,31,4.0,2023-12-31 21:00:00

In [49]:
print(df_visibility["Datetime"].apply(type).value_counts())

Datetime
<class 'pandas._libs.tslibs.timestamps.Timestamp'>    3634745
Name: count, dtype: int64

In [50]:
print(df_visibility.duplicated().sum())  # Check for duplicate rows

91208

In [51]:
# Find duplicate rows
duplicates = df_visibility[df_visibility.duplicated()]

# Show the duplicate rows
duplicates

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility,Datetime
16032,Madaripur,11513,23.166667,90.183333,2018,1,0,1,0.6,2018-01-01 00:00:00
16033,Madaripur,11513,23.166667,90.183333,2018,1,3,1,2.0,2018-01-01 03:00:00
16034,Madaripur,11513,23.166667,90.183333,2018,1,6,1,5.0,2018-01-01 06:00:00
16035,Madaripur,11513,23.166667,90.183333,2018,1,9,1,6.0,2018-01-01 09:00:00
16036,Madaripur,11513,23.166667,90.183333,2018,1,12,1,5.0,2018-01-01 12:00:00
...,...,...,...,...,...,...,...,...,...,...
3588830,Dinajpur,10120,25.650000,88.683333,2023,12,12,31,5.0,2023-12-31 12:00:00
3588831,Dinajpur,10120,25.650000,88.683333,2023,12,15,31,4.0,2023-12-31 15:00:00
3588832,Dinajpur,10120,25.650000,88.683333,2023,12,18,31,4.0,2023-12-31 18:00:00
3588833,Dinajpur,10120,25.650000,88.683333,2023,12,21,31,4.0,2023-12-31 21:00:00
3634556,Kumarkhali,41927,23.866667,89.250000,2020,5,9,31,7.0,2020-05-31 09:00:00

In [52]:
# Remove all duplicate rows (considering all columns)
df_visibility = df_visibility.drop_duplicates()

# Display the cleaned DataFrame
df_visibility

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Visibility,Datetime
0,Dhaka,11111,23.766667,90.383333,1981,1,0,1,4.0,1981-01-01 00:00:00
1,Dhaka,11111,23.766667,90.383333,1981,1,3,1,4.0,1981-01-01 03:00:00
2,Dhaka,11111,23.766667,90.383333,1981,1,6,1,4.0,1981-01-01 06:00:00
3,Dhaka,11111,23.766667,90.383333,1981,1,9,1,4.0,1981-01-01 09:00:00
4,Dhaka,11111,23.766667,90.383333,1981,1,12,1,4.0,1981-01-01 12:00:00
...,...,...,...,...,...,...,...,...,...,...
3634740,Kumarkhali,41927,23.866667,89.250000,2023,12,9,31,6.0,2023-12-31 09:00:00
3634741,Kumarkhali,41927,23.866667,89.250000,2023,12,12,31,5.0,2023-12-31 12:00:00
3634742,Kumarkhali,41927,23.866667,89.250000,2023,12,15,31,5.0,2023-12-31 15:00:00
3634743,Kumarkhali,41927,23.866667,89.250000,2023,12,18,31,5.0,2023-12-31 18:00:00
3634744,Kumarkhali,41927,23.866667,89.250000,2023,12,21,31,4.0,2023-12-31 21:00:00

In [53]:
print(df_visibility.duplicated().sum())  # Check for duplicate rows

0

In [54]:
print(df_visibility.groupby("StationID")["Datetime"].nunique())  # Check number of unique timestamps per station

StationID
10120     90576
10320    116872
10408    111032
10609     93504
10705    116872
10724     87656
10910    119800
11111    125640
11313    116872
11316    116872
11407    113952
11505    116872
11513     72800
11604    116648
11610     90576
11704    116872
11706    111032
11805    111032
11809    105192
11814    111032
11912     96424
11916     32113
11921     99344
11925    105192
11927    113952
11929     90576
12007    102264
12103    102264
12110     99344
41851     17528
41856     17528
41858     81816
41881     14608
41888     17528
41897     17528
41909     96416
41926     78888
41927     16800
41938     17528
41947       224
41958     90576
41977     73048
Name: Datetime, dtype: int64

In [55]:
# Reorganizing columns
df_visibility = df_visibility[[
    'Datetime', 'StationName',
    'StationID', 'Latitude', 'Longitude',
    'Year', 'Month', 'Day', 'Time',
    'Visibility'
]]

# Display the first few rows to confirm
df_visibility.head()

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,Visibility
0,1981-01-01 00:00:00,Dhaka,11111,23.766667,90.383333,1981,1,1,0,4.0
1,1981-01-01 03:00:00,Dhaka,11111,23.766667,90.383333,1981,1,1,3,4.0
2,1981-01-01 06:00:00,Dhaka,11111,23.766667,90.383333,1981,1,1,6,4.0
3,1981-01-01 09:00:00,Dhaka,11111,23.766667,90.383333,1981,1,1,9,4.0
4,1981-01-01 12:00:00,Dhaka,11111,23.766667,90.383333,1981,1,1,12,4.0

## **Data Summary**

In [56]:
print(df_visibility.info())  # Check data types and missing values
print(df_visibility.describe())  # Summary statistics for numeric columns
print(df_visibility["Datetime"].min(), df_visibility["Datetime"].max())  # Verify datetime range
print(df_visibility.duplicated().sum())  # Check for duplicate rows

<class 'pandas.core.frame.DataFrame'>
Index: 3543537 entries, 0 to 3634744
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   Datetime     datetime64[ns]
 1   StationName  object
 2   StationID    int64
 3   Latitude     float64
 4   Longitude    float64
 5   Year         int64
 6   Month        int64
 7   Day          int64
 8   Time         int64
 9   Visibility   float64
dtypes: datetime64[ns](1), float64(3), int64(5), object(1)
memory usage: 297.4+ MB
None
                            Datetime     StationID      Latitude  \
count                        3543537  3.543537e+06  3.543537e+06
mean   2005-05-14 16:19:17.914931456  1.607373e+04  2.330816e+01
min              1981-01-01 00:00:00  1.012000e+04  2.086667e+01
25%              1994-03-12 00:00:00  1.131300e+04  2.248333e+01
50%              2006-09-26 18:00:00  1.170600e+04  2.318333e+01
75%              2015-12-29 09:00:00  1.192900e+04  2.413333e+01
max              2023-12-31 21:00:00  4.197700e+04  2.615000e+01
std                              NaN  1.097470e+04  1.142578e+00

          Longitude          Year         Month           Day          Time  \
count  3.543537e+06  3.543537e+06  3.543537e+06  3.543537e+06  3.543537e+06
mean   9.046337e+01  2.004867e+03  6.521570e+00  1.572892e+01  1.049985e+01
min    8.868333e+01  1.981000e+03  1.000000e+00  1.000000e+00  0.000000e+00
25%    8.953333e+01  1.994000e+03  4.000000e+00  8.000000e+00  3.000000e+00
50%    9.038333e+01  2.006000e+03  7.000000e+00  1.600000e+01  9.000000e+00
75%    9.143333e+01  2.015000e+03  1.000000e+01  2.300000e+01  1.500000e+01
max    9.230000e+01  2.023000e+03  1.200000e+01  3.100000e+01  2.100000e+01
std    1.112781e+00  1.216405e+01  3.448895e+00  8.799770e+00  6.873782e+00

         Visibility
count  3.543537e+06
mean   5.100942e+00
min    1.000000e-01
25%    4.000000e+00
50%    5.000000e+00
75%    6.000000e+00
max    9.970000e+01
std    2.245774e+00
1981-01-01 00:00:00 2023-12-31 21:00:00
0

In [57]:
print(df_visibility.isnull().sum())

Datetime       0
StationName    0
StationID      0
Latitude       0
Longitude      0
Year           0
Month          0
Day            0
Time           0
Visibility     0
dtype: int64

In [58]:
print(df_visibility['Datetime'].is_monotonic_increasing)

False

In [59]:
df_visibility['Visibility'] = df_visibility['Visibility'].round(1)

## **Saving the Data Finally**

In [60]:
# Save the DataFrame to a CSV file
df_visibility.to_csv('/content/drive/MyDrive/Thesis/Research Data/Preprocessed Data/Processed_visibility_data.csv', index=False)